### ISSUE TITLE
《Qt6 QML 中渲染自定义视频帧的改进 2023-05-30 更新》文章中的代码，能提供一份完整的代码学习一下吗？

### ISSUE THREAD

**Issue by ilongshan** [nmgwddj/nmgwddj.github.io#2]
这篇文章中关于qml渲染yuv的代码，初学者不是很理解怎么实现。能提供一份完整的实现学习一下吗？

**Comment by nmgwddj** [comment]
参考：https://github.com/nmgwddj/nmgwddj.github.io/blob/428320b26c359dcf965b542b2eb06daef7601359/source/_posts/2019/2019-05-12_184634-2719.md?plain=1#L2

**Comment by ilongshan** [comment]
好的，谢谢给的参考
